<?php

namespace Database\Seeders;

use App\Models\Client;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("clients")->delete();
        DB::table("clients")->truncate();
        DB::table("clients")->insert([
            [
                'username'          => 'conganh212',
                'password'          => bcrypt(123123),
                'email'             => 'conganh2122003@gmail.com',
                'phone_number'      => '0706085418',
                'fullname'          => 'Lê Công Anh',
                'avatar'            => 'avatar_male.jpg',
                'status'            => '1',
                'gender'            => Client::male,
                'nickname'          => 'Tôm',
                'address'           => '123 Đà Nẵng',
                'date_of_birth'     => '2002-06-02',
            ],
            [
                'username'          => 'minhquan',
                'password'          => bcrypt(123123),
                'email'             => 'quan@gmail.com',
                'phone_number'      => '0706085418',
                'fullname'          => 'Võ Minh Quân',
                'avatar'            => 'avatar_other.jpg',
                'status'            => '1',
                'gender'            => Client::other,
                'nickname'          => 'Quân',
                'address'           => '123 Đà Nẵng',
                'date_of_birth'     => '2002-06-02',
            ],
            [
                'username'          => 'huuhoang',
                'password'          => bcrypt(123123),
                'email'             => 'vuhuuhoang@gmail.com',
                'phone_number'      => '0706085418',
                'fullname'          => 'Vũ Hữu Hoàng',
                'avatar'            => 'avatar_female.jpg',
                'status'            => '1',
                'gender'            => Client::female,
                'nickname'          => 'Hoàng',
                'address'           => '123 Đà Nẵng',
                'date_of_birth'     => '2002-06-02',
            ],
            [
                'username'          => 'duylinh',
                'password'          => bcrypt(123123),
                'email'             => 'linh@gmail.com',
                'phone_number'      => '0706085418',
                'fullname'          => 'Nguyễn Ngọc Hoàng Duy Linh',
                'avatar'            => 'avatar_other.jpg',
                'status'            => '1',
                'gender'            => Client::other,
                'nickname'          => 'Linh',
                'address'           => '123 Đà Nẵng',
                'date_of_birth'     => '2002-06-02',
            ],
            [
                'username'          => 'tanhdeptrai',
                'password'          => bcrypt(123123),
                'email'             => 'phtsnh26@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Phan Công Tánh',
                'avatar'            => 'avatar_male.jpg',
                'status'            => '1',
                'gender'            => Client::male,
                'nickname'          => 'Tánh',
                'address'           => '321 Đà Nẵng',
                'date_of_birth'     => '2002-06-02',
            ],
            [
                'username'          => 'nhingu',
                'password'          => bcrypt(123123),
                'email'             => 'uyennhi@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Nguyễn Lê Uyển Nhi',
                'avatar'            => "avatar_female.jpg",
                'status'            => '1',
                'gender'            => Client::female,
                'nickname'          => 'Nhi Ngu',
                'address'           => '321 Đà Nẵng',
                'date_of_birth'     => '2002-06-02',
            ],
            [
                'username'          => 'thanhthuy',
                'password'          => bcrypt(123123),
                'email'             => 'thuy@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Huỳnh Thị Thanh Thủy',
                'avatar'            => "avatar_female.jpg",
                'status'            => '1',
                'gender'            => Client::female,
                'nickname'          => 'Tít',
                'address'           => '321 Đà Nẵng',
                'date_of_birth'     => '2002-06-02',
            ],
            [
                'username'          => 'thaonguyen',
                'password'          => bcrypt(123123),
                'email'             => 'phanthaonguyen@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Phan Thảo Nguyên',
                'avatar'            => "avatar_female.jpg",
                'status'            => '1',
                'gender'            => Client::female,
                'nickname'          => 'Zen',
                'address'           => '321 Đà Nẵng',
                'date_of_birth'     => '2002-06-02',
            ],
            [
                'username'          => 'phong',
                'password'          => bcrypt(123123),
                'email'             => 'phong@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Hồ Kỳ Phong',
                'avatar'            => "avatar_male.jpg",
                'status'            => '1',
                'gender'            => Client::male,
                'nickname'          => 'Phong Ngu',
                'address'           => '321 Đà Nẵng',
                'date_of_birth'     => '2002-06-02',
            ],
            [
                'username'          => 'ductrong',
                'password'          => bcrypt(123123),
                'email'             => 'nguyenductrong@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Nguyễn Đức Trọng',
                'avatar'            => "avatar_female.jpg",
                'status'            => '1',
                'gender'            => Client::female,
                'nickname'          => 'Trọng',
                'address'           => '321 Đà Nẵng',
                'date_of_birth'     => '2002-06-02',
            ],
            [
                'username'          => 'linhnguyen',
                'password'          => bcrypt(123123),
                'email'             => 'nguyenlinh@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Nguyễn Linh',
                'avatar'            => "avatar_female.jpg",
                'status'            => '1',
                'gender'            => Client::female,
                'nickname'          => 'Linhie',
                'address'           => '321 Hanoi',
                'date_of_birth'     => '2000-10-15',
            ],
            [
                'username'          => 'minhhoang',
                'password'          => bcrypt(123123),
                'email'             => 'hoangminh@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Hoàng Minh',
                'avatar'            => "avatar_male.jpg",
                'status'            => '1',
                'gender'            => Client::male,
                'nickname'          => 'Minhie',
                'address'           => '123 Ho Chi Minh',
                'date_of_birth'     => '1998-05-20',
            ],
            [
                'username'          => 'ngochuyen123',
                'password'          => bcrypt(123123),
                'email'             => 'ngochuyen123@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Ngô Chuyên',
                'avatar'            => "avatar_female.jpg",
                'status'            => '1',
                'gender'            => Client::female,
                'nickname'          => 'Chuyên Nho',
                'address'           => '456 Hanoi',
                'date_of_birth'     => '1995-08-25',
            ],
            [
                'username'          => 'thuylinh',
                'password'          => bcrypt(123123),
                'email'             => 'linhthuy@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Thùy Linh',
                'avatar'            => "avatar_female.jpg",
                'status'            => '1',
                'gender'            => Client::female,
                'nickname'          => 'Linhie',
                'address'           => '789 Ho Chi Minh',
                'date_of_birth'     => '1997-03-12',
            ],
            [
                'username'          => 'ngocanh',
                'password'          => bcrypt(123123),
                'email'             => 'ngocanh@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Ngọc Anh',
                'avatar'            => "avatar_female.jpg",
                'status'            => '1',
                'gender'            => Client::female,
                'nickname'          => 'Anhie',
                'address'           => '101 Da Nang',
                'date_of_birth'     => '1994-11-18',
            ],
            [
                'username'          => 'maihoa',
                'password'          => bcrypt(123123),
                'email'             => 'maihoa@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Mai Hòa',
                'avatar'            => "avatar_female.jpg",
                'status'            => '1',
                'gender'            => Client::female,
                'nickname'          => 'Hòa Mai',
                'address'           => '888 Hanoi',
                'date_of_birth'     => '1996-07-03',
            ],
            [
                'username'          => 'phuonglan',
                'password'          => bcrypt(123123),
                'email'             => 'phuonglan@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Phương Lan',
                'avatar'            => "avatar_female.jpg",
                'status'            => '1',
                'gender'            => Client::female,
                'nickname'          => 'Lan Phương',
                'address'           => '999 Ho Chi Minh',
                'date_of_birth'     => '1993-04-30',
            ],
            [
                'username'          => 'vananh',
                'password'          => bcrypt(123123),
                'email'             => 'vananh@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Vân Anh',
                'avatar'            => "avatar_other.jpg",
                'status'            => '1',
                'gender'            => Client::other,
                'nickname'          => 'Anh Vân',
                'address'           => '222 Hanoi',
                'date_of_birth'     => '1990-12-15',
            ],
            [
                'username'          => 'minhthu',
                'password'          => bcrypt(123123),
                'email'             => 'minhthu@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Minh Thu',
                'avatar'            => "avatar_other.jpg",
                'status'            => '1',
                'gender'            => Client::other,
                'nickname'          => 'Thu Minh',
                'address'           => '333 Ho Chi Minh',
                'date_of_birth'     => '1992-05-20',
            ],
            [
                'username'          => 'thanhhoa',
                'password'          => bcrypt(123123),
                'email'             => 'thanhhoa@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Thanh Hòa',
                'avatar'            => "avatar_other.jpg",
                'status'            => '1',
                'gender'            => Client::other,
                'nickname'          => 'Hòa Thanh',
                'address'           => '444 Hanoi',
                'date_of_birth'     => '1988-11-18',
            ],
            [
                'username'          => 'quynhtrang',
                'password'          => bcrypt(123123),
                'email'             => 'quynhtrang@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Quỳnh Trang',
                'avatar'            => "avatar_other.jpg",
                'status'            => '1',
                'gender'            => Client::other,
                'nickname'          => 'Trang Quỳnh',
                'address'           => '555 Da Nang',
                'date_of_birth'     => '1991-07-03',
            ],
            [
                'username'          => 'thihien',
                'password'          => bcrypt(123123),
                'email'             => 'thihien@gmail.com',
                'phone_number'      => '0321321321',
                'fullname'          => 'Thi Hiền',
                'avatar'            => "avatar_other.jpg",
                'status'            => '1',
                'gender'            => Client::other,
                'nickname'          => 'Hiền Thi',
                'address'           => '666 Ho Chi Minh',
                'date_of_birth'     => '1989-04-30',
            ],
            [
                'username'       => 'hongnga',
                'password'       => bcrypt(123123),
                'email'          => 'hongnga@gmail.com',
                'phone_number'   => '0321321321',
                'fullname'       => 'Hồng Nga',
                'avatar'         => 'avatar_female.jpg',
                'status'         => '1',
                'gender'         => Client::female,
                'nickname'       => 'Nga Hồng',
                'address'        => '456 Hue',
                'date_of_birth'  => '1994-09-18',
            ],
            [
                'username'       => 'khanhtung',
                'password'       => bcrypt(123123),
                'email'          => 'khanhtung@gmail.com',
                'phone_number'   => '0321321321',
                'fullname'       => 'Khánh Tùng',
                'avatar'         => 'avatar_male.jpg',
                'status'         => '1',
                'gender'         => Client::male,
                'nickname'       => 'Tùng Khánh',
                'address'        => '789 Ho Chi Minh',
                'date_of_birth'  => '1992-05-12',
            ],
            [
                'username'       => 'tramy',
                'password'       => bcrypt(123123),
                'email'          => 'tramy@gmail.com',
                'phone_number'   => '0321321321',
                'fullname'       => 'Trà My',
                'avatar'         => 'avatar_female.jpg',
                'status'         => '1',
                'gender'         => Client::female,
                'nickname'       => 'My Trà',
                'address'        => '111 Da Nang',
                'date_of_birth'  => '1993-03-25',
            ],
            [
                'username'       => 'quanphuc',
                'password'       => bcrypt(123123),
                'email'          => 'quanphuc@gmail.com',
                'phone_number'   => '0321321321',
                'fullname'       => 'Quân Phúc',
                'avatar'         => 'avatar_male.jpg',
                'status'         => '1',
                'gender'         => Client::male,
                'nickname'       => 'Phúc Quân',
                'address'        => '987 Can Tho',
                'date_of_birth'  => '1997-11-08',
            ],
            [
                'username'       => 'ngochuyen',
                'password'       => bcrypt(123123),
                'email'          => 'ngochuyen@gmail.com',
                'phone_number'   => '0321321321',
                'fullname'       => 'Ngọc Huyền',
                'avatar'         => 'avatar_female.jpg',
                'status'         => '1',
                'gender'         => Client::female,
                'nickname'       => 'Huyền Ngọc',
                'address'        => '654 Hai Phong',
                'date_of_birth'  => '1995-12-03',
            ],
            [
                'username'       => 'hoainam',
                'password'       => bcrypt(123123),
                'email'          => 'hoainam@gmail.com',
                'phone_number'   => '0321321321',
                'fullname'       => 'Hòa Nam',
                'avatar'         => 'avatar_male.jpg',
                'status'         => '1',
                'gender'         => Client::male,
                'nickname'       => 'Nam Hòa',
                'address'        => '333 Hue',
                'date_of_birth'  => '1998-04-22',
            ],
            [
                'username'       => 'tranghien',
                'password'       => bcrypt(123123),
                'email'          => 'tranghien@gmail.com',
                'phone_number'   => '0321321321',
                'fullname'       => 'Trang Hiền',
                'avatar'         => 'avatar_female.jpg',
                'status'         => '1',
                'gender'         => Client::female,
                'nickname'       => 'Hiền Trang',
                'address'        => '111 Ho Chi Minh',
                'date_of_birth'  => '1996-09-10',
            ],
            [
                'username'       => 'tienthanh',
                'password'       => bcrypt(123123),
                'email'          => 'tienthanh@gmail.com',
                'phone_number'   => '0321321321',
                'fullname'       => 'Tiến Thành',
                'avatar'         => 'avatar_male.jpg',
                'status'         => '1',
                'gender'         => Client::male,
                'nickname'       => 'Thành Tiến',
                'address'        => '555 Da Nang',
                'date_of_birth'  => '1993-12-05',
            ],
            [
                'username'       => 'lanan',
                'password'       => bcrypt(123123),
                'email'          => 'lanan@gmail.com',
                'phone_number'   => '0321321321',
                'fullname'       => 'Lã An',
                'avatar'         => 'avatar_female.jpg',
                'status'         => '1',
                'gender'         => Client::female,
                'nickname'       => 'An Lã',
                'address'        => '777 Can Tho',
                'date_of_birth'  => '1992-07-18',
            ],
            [
                'username'       => 'minhtuan',
                'password'       => bcrypt(123123),
                'email'          => 'minhtuan@gmail.com',
                'phone_number'   => '0321321321',
                'fullname'       => 'Minh Tuấn',
                'avatar'         => 'avatar_male.jpg',
                'status'         => '1',
                'gender'         => Client::male,
                'nickname'       => 'Tuấn Minh',
                'address'        => '888 Hai Phong',
                'date_of_birth'  => '1997-02-14',
            ],
            [
                'username'       => 'thienhong',
                'password'       => bcrypt(123123),
                'email'          => 'thienhong@gmail.com',
                'phone_number'   => '0321321321',
                'fullname'       => 'Thiên Hồng',
                'avatar'         => 'avatar_female.jpg',
                'status'         => '1',
                'gender'         => Client::female,
                'nickname'       => 'Hồng Thiên',
                'address'        => '444 Hue',
                'date_of_birth'  => '1991-05-28',
            ],
            [
                'username'       => 'quanminh',
                'password'       => bcrypt(123123),
                'email'          => 'quanminh@gmail.com',
                'phone_number'   => '0321321321',
                'fullname'       => 'Phan Quân Minh',
                'avatar'         => 'avatar_male.jpg',
                'status'         => '1',
                'gender'         => Client::male,
                'nickname'       => 'Quân Minh',
                'address'        => '666 Ho Chi Minh',
                'date_of_birth'  => '1990-08-12',
            ],
            [
                'username'       => 'thuhuong',
                'password'       => bcrypt(123123),
                'email'          => 'thuhuong@gmail.com',
                'phone_number'   => '0321321321',
                'fullname'       => 'Thu Hương',
                'avatar'         => 'avatar_female.jpg',
                'status'         => '1',
                'gender'         => Client::female,
                'nickname'       => 'Hương Thu',
                'address'        => '123 Da Nang',
                'date_of_birth'  => '1994-02-09',
            ],
            [
                'username'       => 'thanhtruong',
                'password'       => bcrypt(123123),
                'email'          => 'thanhtruong@gmail.com',
                'phone_number'   => '0321321321',
                'fullname'       => 'Phạm Thanh Trường',
                'avatar'         => 'avatar_male.jpg',
                'status'         => '1',
                'gender'         => Client::male,
                'nickname'       => 'Em sinh viên',
                'address'        => 'Đà Nẵng',
                'date_of_birth'  => '2001-10-15',
            ],
            [
                'username'       => 'ngocdiep',
                'password'       => bcrypt(123123),
                'email'          => 'ngocdiep@gmail.com',
                'phone_number'   => '0321321321',
                'fullname'       => 'Ngọc Diệp',
                'avatar'         => 'avatar_female.jpg',
                'status'         => '1',
                'gender'         => Client::female,
                'nickname'       => 'Diệp Ngọc',
                'address'        => '222 Hai Phong',
                'date_of_birth'  => '1996-11-20',
            ],
            [
                'username'       => 'dangquang',
                'password'       => bcrypt(123123),
                'email'          => 'quang@gmail.com',
                'phone_number'   => '0321321321',
                'fullname'       => 'Phạm Đăng Quang',
                'avatar'         => 'avatar_female.jpg',
                'status'         => '1',
                'gender'         => Client::male,
                'nickname'       => 'Quang Không Ngu',
                'address'        => 'Đà Nẵng',
                'date_of_birth'  => '2002-11-20',
            ],
        ]);
    }
}
